Repository SE310-1/W.A.K, pull requests merged in 2023-09, with the labels that each got.

#57 Implement Basic Version of Favourites Page
  .vs/ProjectSettings.json
  .vs/VSWorkspaceState.json
  .vs/slnx.sqlite
  client/src/App.jsx
  client/src/Components/Navbar/index.jsx
  client/src/Pages/Favourites/index.jsx
  client/src/Pages/Favourites/style.css
Labels: enhancement

#59 Create add friends feature
  client/src/Functions/acceptFriendRequest.js
  client/src/Functions/addFriend.js
  client/src/Functions/declineFriendRequest.js
  client/src/Hooks/useFriendRequests.js
  client/src/Hooks/useFriends.js
  client/src/Hooks/useSearchUsers.js
  server/index.js
  server/src/models/userModel.js
Labels: enhancement

#63 Create a functioning favourites list
  client/src/Components/FavouritesList/index.jsx
  client/src/Components/FavouritesList/style.css
  client/src/Components/MovieCard/index.jsx
  client/src/Hooks/useFavourites.js
  client/src/Pages/Favourites/index.jsx
  server/index.js
  server/src/models/userModel.js
Labels: enhancement

#62 Add comments
  client/src/Hooks/useAuthContext.js
  client/src/Hooks/useLogin.js
  client/src/Hooks/useLogout.js
  client/src/Hooks/useRating.js
  client/src/Hooks/useSignup.js
  server/src/middleware/requireAuth.js
  server/src/models/ratingModel.js
  server/src/models/userModel.js
Labels: documentation, refactor

#70 Refactor js files.
  client/src/Functions/acceptFriendRequest.js
  client/src/Functions/addFriend.js
  client/src/Functions/declineFriendRequest.js
  client/src/Hooks/useFavourites.js
  client/src/Hooks/useLogin.js
  client/src/Hooks/useLogout.js
  client/src/Hooks/useRating.js
Labels: refactor

#74 Add theming based on user's favourites list
  client/package-lock.json
  client/package.json
  client/src/Components/Navbar/index.tsx
  client/src/Components/Navbar/style.css
  client/src/Functions/computeThemeColourAndImage.jsx
  client/src/Hooks/useTheme.js
  client/src/Pages/Favourites/index.jsx
Labels: enhancement

#76 Favourite Button Styling
  client/src/Components/DeleteFavoriteButton/index.tsx
  client/src/Components/DeleteFavoriteButton/style.css
  client/src/Components/FavoriteButton/index.tsx
  client/src/Components/FavoriteButton/style.css
Labels: enhancement

#77 Additional Commenting
  client/src/Components/DeleteFavoriteButton/index.tsx
  client/src/Components/FavoriteButton/index.tsx
  client/src/Components/FavouritesList/index.tsx
  client/src/Components/Navbar/index.tsx
  client/src/Components/Sharebutton/index.tsx
  client/src/Hooks/useFavourites.js
  client/src/Pages/Friends/index.tsx
Labels: documentation
