Repository SE310-1/W.A.K, pull requests merged in 2023-10, with the labels that each got.

#85 Friend modal UI
  client/src/Assets/close-icon-fill.png
  client/src/Assets/close-icon.png
  client/src/Assets/index.d.tsx
  client/src/Assets/left-arrow-fill.png
  client/src/Assets/left-button.png
  client/src/Assets/profile-img.jpg
  client/src/Assets/right-arrow-fill.png
  client/src/Assets/right-button.png
  client/src/Components/FriendModal/index.tsx
  client/src/Components/FriendModal/style.css
  client/src/Components/FriendRequestListCard/index.tsx
  client/src/Components/FriendRequestListCard/style.css
  client/src/Components/MovieSlider/index.tsx
  client/src/Components/MovieSlider/style.css
  client/src/Constants/images.tsx
  client/src/Constants/index.tsx
  client/src/Pages/Friends/index.tsx
Labels: enhancement

#88 Skau811 favlist custom order frontend
  client/src/Components/DeleteFavoriteButton/index.tsx
  client/src/Components/DeleteFavoriteButton/style.css
  client/src/Components/FavoriteButton/index.tsx
  client/src/Components/FavoriteButton/style.css
  client/src/Components/FavouritesList/index.tsx
  client/src/Components/FavouritesList/style.css
  client/src/Components/Navbar/index.tsx
  client/src/Components/Navbar/style.css
  client/src/Functions/computeThemeColourAndImage.jsx
  client/src/Hooks/useTheme.js
  client/src/Pages/Details/index.jsx
  client/src/Pages/Details/styles.css
  client/src/Pages/Favourites/index.jsx
  client/src/Pages/Favourites/style.css
  server/index.js
Labels: enhancement, Run `npm run installAll` After Pulling

#87 Ahop089 modal
  client/src/Components/DeleteFavoriteButton/index.tsx
  client/src/Components/FavoriteButton/index.tsx
  client/src/Components/FriendModal/index.tsx
  client/src/Components/MediaGrid/index.tsx
  client/src/Components/MovieSlider/index.tsx
  client/src/Hooks/useFavourites.js
  server/index.js
  server/src/models/userModel.js
Labels: do not merge

#95 Add Google Auth UI
  client/package-lock.json
  client/package.json
  client/src/Components/SocialLogin/index.tsx
  client/src/Pages/Login/index.jsx
  client/src/Pages/Signup/index.jsx
Labels: enhancement, Run `npm run installAll` After Pulling

#96 Removing Facebook sign-in
  client/src/Pages/Login/index.jsx
  client/src/Pages/Signup/index.jsx
Labels: bug

#97 Implement Google Authentication Client Side Logic
  client/src/Hooks/useGoogleAuth.ts
  client/src/Pages/Login/index.jsx
  client/src/Pages/Login/style.css
  client/src/Pages/Signup/index.jsx
  package-lock.json
  package.json
  tsconfig.json
Labels: enhancement, Run `npm run installAll` After Pulling
